/**
 * Schema-derived database models and enum unions.
 *
 * The legacy `@/db/types` module remains supported while callers migrate to
 * these narrower imports.
 */
export type {
    UserRole,
    SubmissionStatus,
    ReviewStatus,
    ReviewDecision,
    PaymentStatus,
    ApplicationStatus,
    ApplicationType,
    ContactStatus,
    VolumeIssueStatus,
    FileType,
    FinalDecision,
    GalleyStatus,
    NotificationType,
    DoiProvider,
    DoiRegistrationStatus,
    User,
    NewUser,
    UserProfile,
    NewUserProfile,
    Submission,
    NewSubmission,
    Version,
    NewVersion,
    SubmissionFile,
    Author,
    ReviewAssignment,
    NewReviewAssignment,
    Review,
    NewReview,
    Payment,
    NewPayment,
    Publication,
    Issue,
    Application,
    NewApplication,
    ApplicationInterest,
    NewApplicationInterest,
    ContactMessage,
    NewContactMessage,
    Notification,
    ActivityLog,
    Setting,
    EmailTemplate,
    NewEmailTemplate,
    ChatMessage,
    NewChatMessage,
    PushSubscriptionRow,
    NewPushSubscriptionRow,
    Section,
    NewSection,
    ReviewerSuggestion,
    NewReviewerSuggestion,
    SubmissionEventLogEntry,
    NewSubmissionEventLogEntry,
    AnnouncementType,
    Announcement,
    NewAnnouncement,
    StaticPage,
    NewStaticPage,
    UsageStat,
    NewUsageStat,
} from './types';

export { SUBMISSION_EVENT_TYPES } from './types';
export type { SubmissionEventType } from './types';
